apiVersion: v1
kind: Service
metadata:
  name: service1
spec:
  selector:
    app: service1
  ports:
  - port: 5001
    targetPort: 5001
    nodePort: 30001
  type: NodePort

---

apiVersion: v1
kind: Service
metadata:
  name: service2
spec:
  selector:
    app: service2
  ports:
  - port: 5000
    targetPort: 5000
    nodePort: 30000
  type: NodePort  

